### PR TITLE
Added pure SSDP M-SEARCH

### PR DESCRIPTION
**Pull request by mnaiman**

### CODE REVIEW

**Comment by mnaiman** [comment]
Hi, I have extended your work, so there is pull if you want to take a look.

**Comment by deonvdw** [comment]
Thank you for the pull request. I am a little bit busy right now, will try and look at it soon.

**Comment by deonvdw** [comment]
Hi @mnaiman (and @Baune8D)

What is the use case for the subnet filters? The original code already checks that a source packet arrives on a managed (i.e. specified on the command line with **--dev**) interface and drops it if it comes from any other interface. I'm not sure what subnet filtering adds on top of this? Unless you have some sort of hierarchy of udp broadcast proxies?

On the subnet filter code itself:

- Rather convert the CIDR to a network number and netmask once during command line processing (line 1588 in your main.c)  instead of doing it for every received packet (line 2014). Doing it per packet wastes a lot of CPU. Then store a list of network number and netmasks instead of text strings.
- Line 2016: you want to catch this when processing the command line and not just randomly exit when already forwarding packets. Taken care of by above point.
- Why split the subnet logic in two pieces (line 2005-2024 and 2057-2061)? I would move it all to the second (line 2057) section

For the pure M-SEARCH mode:

- Perhaps we can make the pure M-SEARCH mode automatic? The location service and REST proxies are only really relevant for M-SEARCH requests with the "ST: urn:dial-multiscreen-org:service:dial:1" search term. We can turn off the location service and REST proxies if this text is not found. Then again - maybe we want to add functionality to turn M-SEARCH proxying on and off for specific ST: search terms to only let certain M-SEARCH requests through.
- The changes in service_proxy_messages() is unnecessary. There is no need to check proxy type as location services/rest proxies will only receive traffic if find_or_create_locsvc_listener() was called (line 1200 in your main.c)

Your thoughts?

**Comment by Baune8D** [comment]
Hi @deonvdw let me try to explain what my use-case with subnet filtering is.

Mostly it is to avoid relayed packages from one udpbroadcastrelay instance, being picked up by another one.

As an example lets say i have these 2 IoT vlans:
* A Sonos network for all my Sonos speakers: `10.0.31.0/24`  (`ens1.31`)
* A Google network for all my Chromecasts and Google Home devices: `10.0.32.0/24` (`ens1.32`)

Then i have my home network: `10.0.10.0/24` (`ens1`)

I have a couple of udpbroadcastrelay instances setup like this:
```bash
sudo udpbroadcastrelay --id 1 --port 1900 --dev ens1 --dev ens1.31 --multicast 239.255.255.250 -f
sudo udpbroadcastrelay --id 2 --port 5353 --dev ens1 --dev ens1.31 --multicast 224.0.0.251 -s 1.1.1.1 -f
sudo udpbroadcastrelay --id 3 --port 5353 --dev ens1 --dev ens1.32 --multicast 224.0.0.251 -s 1.1.1.1 -f
```

What i want is for my home network to be able to see and communicate with devices on both the Sonos and Google network. But i do not want the Sonos and Google network to be able to see each other.

Right now the third instance will pick up packages relayed from `ens1.31` to `ens1`, and relay them again to `ens1.32`.

Instead my setup with my changes looks like this:
```bash
sudo udpbroadcastrelay --id 1 --port 1900 --dev ens1 --dev ens1.31 --subnet 10.0.10.0/24 --subnet 10.0.31.0/24 --multicast 239.255.255.250 -f
sudo udpbroadcastrelay --id 2 --port 5353 --dev ens1 --dev ens1.31 --subnet 10.0.10.0/24 --subnet 10.0.31.0/24 --multicast 224.0.0.251 -s 1.1.1.1 -f
sudo udpbroadcastrelay --id 3 --port 5353 --dev ens1 --dev ens1.32 --subnet 10.0.10.0/24 --subnet 10.0.32.0/24 --multicast 224.0.0.251 -s 1.1.1.1 -f
```

Now packages not originating from `10.0.10.0/24` will not be relayed to `ens1.32`

I will try to look into the changes you proposed 🙂 But C is really not a strength of mine, so the changes i have made so far was already a big challenge for me 😄

**Comment by Baune8D** [comment]
Also i am not really involved with this PR. I have my own fork here https://github.com/Baune8D/udpbroadcastrelay but will gladly contribute if it makes any sense 🙂

**Comment by deonvdw** [comment]
Hi Morten,

Thank you for explaining your use case. udpbroadcastrelay already has a check to not to forward UDP packets from the same **--id** value (normally stored in the DSCP/TOS field). I am tempted to extend this mechanism to allow you to block traffic from other instances. Something like a **--blockid** X option where X would match the **--id** value from the other instance.

Regardless of the above, let me pull in the subnet blocking code. Don't worry about fixing up the C - I'll take care of the suggested changes. 🙂

**Comment by Baune8D** [comment]
@deonvdw I can see you have committed the blockid option on your repo. Please till me when you think it is in a stable condition. I would love to try it out here myself instead of using the subnet blocking 🙂

**Comment by deonvdw** [comment]
@Baune8D - I've verified the **--blockid** functionality in my lab environment and it is currently stable. Unless you manage to find a bug 🙂 🙂 🙂.

I am planning a few changes around the M-SEARCH proxy code though, and will push that once it is completed and tested.

**Comment by Baune8D** [comment]
Hi @deonvdw I just updated my Ubuntu machine to 22.04 and tried to build your newest version. It now fails on `make` with:

```
cc  -g main.c -o udpbroadcastrelay
main.c: In function ‘printtime’:
main.c:256:9: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  256 |     if (gettimeofday(&tv,NULL) == -1)
      |         ^~~~~~~~~~~~
main.c:259:10: warning: implicit declaration of function ‘localtime’ [-Wimplicit-function-declaration]
  259 |     tm = localtime(&now);
      |          ^~~~~~~~~
main.c:259:8: warning: assignment to ‘struct tm *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  259 |     tm = localtime(&now);
      |        ^
main.c:261:53: error: invalid use of undefined type ‘struct tm’
  261 |     printf("%04i/%02i/%02i %02i:%02i:%02i.%03i ", tm->tm_year + 1900, tm->tm_mon + 1,
      |                                                     ^~
main.c:261:73: error: invalid use of undefined type ‘struct tm’
  261 |     printf("%04i/%02i/%02i %02i:%02i:%02i.%03i ", tm->tm_year + 1900, tm->tm_mon + 1,
      |                                                                         ^~
main.c:262:14: error: invalid use of undefined type ‘struct tm’
  262 |            tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, millisec);
      |              ^~
main.c:262:27: error: invalid use of undefined type ‘struct tm’
  262 |            tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, millisec);
      |                           ^~
main.c:262:40: error: invalid use of undefined type ‘struct tm’
  262 |            tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, millisec);
      |                                        ^~
main.c:262:52: error: invalid use of undefined type ‘struct tm’
  262 |            tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, millisec);
      |                                                    ^~
main.c: In function ‘find_or_create_restsvc_listener’:
main.c:485:18: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
  485 |     time_t now = time(NULL);
      |                  ^~~~
main.c: In function ‘handle_msearch_proxy_recv’:
main.c:1272:65: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
 1272 |             DPRINT("   Updating M-SEARCH Locator address from %.*s to %s\n",
      |                                                               ~~^~
      |                                                                 |
      |                                                                 int
 1273 |                    (addrEndPtr-addrStartPtr), addrStartPtr, addrstr);
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               long int
main.c: In function ‘handle_locsvc_proxy_recv’:
main.c:1110:53: warning: ‘%s’ directive output may be truncated writing up to 254 bytes into a region of size 64 [-Wformat-truncation=]
 1110 |                 snprintf(addrstr, sizeof(addrstr), "%s:%d", proxyAddrStr, proxyPort);
      |                                                     ^~      ~~~~~~~~~~~~
main.c:1110:17: note: ‘snprintf’ output between 3 and 261 bytes into a destination of size 64
 1110 |                 snprintf(addrstr, sizeof(addrstr), "%s:%d", proxyAddrStr, proxyPort);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘handle_msearch_proxy_recv’:
main.c:1271:49: warning: ‘%s’ directive output may be truncated writing up to 254 bytes into a region of size 64 [-Wformat-truncation=]
 1271 |             snprintf(addrstr, sizeof(addrstr), "%s:%d", proxyAddrStr, proxyPort);
      |                                                 ^~      ~~~~~~~~~~~~
main.c:1271:13: note: ‘snprintf’ output between 3 and 261 bytes into a destination of size 64
 1271 |             snprintf(addrstr, sizeof(addrstr), "%s:%d", proxyAddrStr, proxyPort);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:4: udpbroadcastrelay] Error 1
```

**Comment by deonvdw** [comment]
@Baune8D That was embarrassing! :( I forgot to include the proper header files for the time functions, and somehow it still compiled fine on FreeBSD 12. I've fixed the missing header files and a few other bits so the code now compiles without any warnings on FreeBSD 12 and Ubuntu 20.04.4 LTS.

**Comment by Baune8D** [comment]
Yes that solved the issue! Built with no warnings and errors on Ubuntu 22.04 🙂

**Comment by deonvdw** [comment]
Thank you @mnaiman and @Baune8D for your great ideas. I've now implemented a more generalized version of the pull request.

**Pull request closed without merging**
